openmrs/openmrs-sdk

- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/OpenmrsBintrayIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SdkMatchers.java
- maven-plugin/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/Bintray.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/BintrayFile.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/BintrayId.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/BintrayPackage.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/OpenmrsBintray.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
- pom.xml
1. add `Bintray` class to interact with Bintray's Rest API and `OpenmrsBintray` to easily obtain packages from openmrs repositories on Bintray
2. add `Deploy OpenMRS OWA` option to `deploy` task  in interactive and batch mode (eg parameter `-Dowa=conceptdictionary:1.0.0-beta.6`)
3. store OWAs installed by user in server properties
4. create appropriate integration tests
> SDK-86 Install Open Web App

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Project.java
Workflow: 
-tempProject folder with modules from watched projects is created
-pom.xml of each module is extended by parent
-pom.xml of tempProject is created
-"mvn clean instal" in tempProject
-deploying modules to server
I will try to add some  integration test
> SDK-101 building and deploying module before run

- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
This PR is clone of https://github.com/openmrs/openmrs-contrib-sdk-maven-plugin/pull/39 and it will be ready to merge when fixes suggested by @rkorytkowski are applied
> SDK-96 - Added JDK choose option

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Pull.java
@rkorytkowski I've found one problem with Jgit which I can't resolve. To reproduce it please try to pull changes from project directory with one commit that will be in conflict with master. (no uncommieted changes). 
after doing rebase --abort there are some modified files. I was trying to stash them but it didn't work
> SDK-104 pull rebase if git project present

- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/PullIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
There are tests also for SDK-104(currently ignored), will be added after SDK-104 merge
> SDK-102 tests added for pull goal

- .travis.yml
- deploy.sh
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SettingsManager.java
- maven-plugin/src/main/resources/settings.xml
- pom.xml
To make it all work:
1) generate personal access token. Go to https://github.com/settings/tokens
2) add three environment variables to travis CI: 
- BINTRAY_USER
- BINTRAY_API_KEY - go to https://bintray.com/profile/edit -> API key
- GITHUB_API_KEY - the one generated above
3) Go to Bintray and create new openmrs-sdk package in maven repo
> SDK-121 release SDK to Bintray on Git tag

- integration-tests/src/test/java/org/openmrs/maven/plugins/OpenmrsBintrayIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Pull.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/PullRequest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Release.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/SetupSDK.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/Bintray.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/CreatePackageRequest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/OpenmrsBintray.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/git/DefaultGitHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/git/GitHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultJira.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Jira.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SettingsManager.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/PullRequestTest.java
https://issues.openmrs.org/browse/SDK-122
> SDK-122 Release any maven project to bintray

- integration-tests/src/test/java/org/openmrs/maven/plugins/CloneIntegrationTest.java
- maven-plugin/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Clone.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Project.java
- pom.xml
> SDK-103 - Clone a module

- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Clone.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateProject.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Help.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Info.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Pull.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Release.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/SetupSDK.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Undeploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Unwatch.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Watch.java
This was causing null pointer exception
> SDK-126 deleted redundand wizard from Watch.class

- maven-plugin/src/main/java/org/openmrs/maven/plugins/ServerUpgrader.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/model/ServerTest.java
This PR adresses comments from #57.
> SDK-124 follow-up: fix getting server modules logic

- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
I will test it tomorrow on Windows machine
> SDK-140 dbUri default with docker machine ip

- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/VersionsHelper.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/utility/VersionsHelperTest.java
https://issues.openmrs.org/browse/SDK-137
> SDK-137 Fix suggested versions

- maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateProject.java
- maven-plugin/src/main/resources/npm
- maven-plugin/src/main/resources/npm.cmd
After creating OWA, all files are removed except node directory.
I'm coping both npm and npm.cmd scripts to the OWA, but I'm not sure about that. Should I copy npm.cmd on Windows os and npm on  non windows os ?
> SDK-85 fixed node cmd for windows

- maven-plugin/src/main/resources/settings.xml
https://issues.openmrs.org/browse/SDK-147
> SDK-147 Add openmrs bintray maven repository to users settings.xml

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Release.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/Bintray.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/OpenmrsBintray.java
https://issues.openmrs.org/browse/SDK-148
> SDK-148 Release omods to bintray

- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SettingsManager.java
https://issues.openmrs.org/browse/SDK-155
> SDK-155 fix setup-sdk failing to setup new settings.xml

- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildDistroIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
- maven-plugin/src/main/resources/build-distro/Dockerfile-jre7
- maven-plugin/src/main/resources/build-distro/Dockerfile-jre8
- maven-plugin/src/main/resources/build-distro/docker-compose.yml
- maven-plugin/src/main/resources/build-distro/setenv.sh
https://issues.openmrs.org/browse/SDK-153
> SDK-153 Add build-distro feature

- integration-tests/src/test/resources/integration-test/buildIT/module1/pom.xml
- integration-tests/src/test/resources/integration-test/buildIT/module2/pom.xml
https://issues.openmrs.org/browse/SDK-157
> SDK-157 change openmrs version in test modules to fix failing build

- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Build.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
https://issues.openmrs.org/browse/SDK-156
> SDK-156 Build goal should detect a maven project and build it

- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/SdkStatistics.java
- maven-plugin/src/main/resources/sdk-stats.properties
Fixed incrementing goals plus added new build-distro goal to SDK and google form
> SDK-158 fixed incrementing goal in sdkStats

- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildDistroIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Build.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Artifact.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
- maven-plugin/src/main/resources/build-distro/Dockerfile-jre7
- maven-plugin/src/main/resources/build-distro/Dockerfile-jre8
- maven-plugin/src/main/resources/build-distro/docker-compose.yml
- maven-plugin/src/main/resources/build-distro/startup.sh
- maven-plugin/src/main/resources/build-distro/wait-for-it.sh
https://issues.openmrs.org/browse/SDK-153
> SDK-153 followup: fix NPE and improve workflow

- maven-plugin/src/main/resources/settings.xml
https://issues.openmrs.org/browse/SDK-147
> SDK-147 Add bintray pluginRepository to user's settings.xml

- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SdkMatchers.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Reset.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/ServerUpgrader.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Undeploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/UpgradeDifferential.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/ModuleInstaller.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/model/DistroPropertiesTest.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/utility/DistroHelperTest.java
@rkorytkowski This is not finished yet. Any feedback will be appreciated :)
> SDK-136 modified deploy module to work with server properties

- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SdkMatchers.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
Workflow described [here](https://issues.openmrs.org/browse/SDK-152)
> SDK-152 Set debug mode at server creation time

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
https://issues.openmrs.org/browse/SDK-168
> SDK-168 fix setup with dbSql=null flag

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Build.java
https://issues.openmrs.org/browse/SDK-172
> SDK-172 Fix failing openmrs-core build when watched

- archetype-module-platform/src/main/resources/archetype-resources/pom.xml
- archetype-module-refapp/src/main/resources/archetype-resources/pom.xml
https://issues.openmrs.org/browse/SDK-165
> SDK-165 Add OpenMRS Maven Repos to Newly Created Module

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
https://issues.openmrs.org/browse/SDK-176
> SDK-176 fixes bug when deploying watched modules

- pom.xml
See [SDK-160](https://issues.openmrs.org/browse/SDK-160) for details.
> SDK-160 - Fixed forked Tomcat process on Windows

- archetype-submodule-owa/pom.xml
- archetype-submodule-owa/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetype-submodule-owa/src/main/resources/archetype-resources/assembly.xml
- archetype-submodule-owa/src/main/resources/archetype-resources/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AddFeature.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/OwaHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/XmlHelper.java
- maven-plugin/src/main/resources/archetype-submodule-owa/config.xml
- maven-plugin/src/main/resources/archetype-submodule-owa/omod.pom.xml
- maven-plugin/src/main/resources/archetype-submodule-owa/owa.gitignore
- maven-plugin/src/test/java/org/openmrs/maven/plugins/utility/XmlHelperTest.java
- pom.xml
https://issues.openmrs.org/browse/SDK-142
> SDK-142 Add add-feature goal

- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
@rkorytkowski 
I didn't add any new test so if you want some don't merge this and let me know. I will add them next week :)
> AC-182 Deploy shows incorrect platform versions

- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- integration-tests/src/test/resources/integration-test/distro-properties/openmrs-distro.properties
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/ServerUpgrader.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/ModuleInstaller.java
TODO:
Thanks @AdamGrzybkowski for help on this ticket :)
> SDK-185 - Ability to define parent distro in openmrs-distro.properties

- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
Files that are being updated: openmrs.war, modules, openmrs-distro.properties and dump.sql the rest is remaining the same.
> SDK-190 Update modules and war only when building distro

- maven-plugin/src/main/resources/help.yaml
The goals create-module/create-plaftform-module have been replaced by create-project. The help section is changed to reflect these changes.
> SDK-226: Remove help for create-module/create-platform-module goals.

- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Artifact.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/model/ArtifactTest.java
https://issues.openmrs.org/browse/SDK-235 with original discussion https://talk.openmrs.org/t/custom-module-development-importing-all-dependencies-from-existing-module-and-extending-openmrs-distro-properties-file/18588/15
> SDK-235 Enable artifact names to contain dashes

- pom.xml
https://issues.openmrs.org/browse/SDK-249
Upgrading tomcat from 7.96 to 7.99 since the latest version getting bundled in the docker image is 7.99
> SDK-249 Upgrade Tomcat from 7.96 to 7.99

- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractDockerMojo.java
- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateMySql.java
- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/RunDb.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AddFeature.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Build.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Clone.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateProject.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Delete.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Fetch.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Info.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Pull.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/PullRequest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Release.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Reset.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Undeploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Unwatch.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Watch.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/WatchOwa.java
ticket id:https://issues.openmrs.org/browse/SDK-247
Description
fixed deprecated warnings that occur during the building of SDK
> SDK-247:Fix warnings when building SDK

- maven-plugin/src/main/resources/settings.xml
- pom.xml
https://issues.openmrs.org/browse/SDK-252
cc @ibacher ,@dkayiwa
> SDK-252: Updating settings.xml

- maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/OpenMRSSDKRedirectServlet.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/OpenMRSSDKRedirectServletTest.java
…p://localhost:port/openmrs
**Issue worked on**: https://issues.openmrs.org/browse/SDK-193
> SDK-193: Automatically redirect Tomcat to OpenMRS Context

- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Reset.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/ModuleInstaller.java
https://issues.openmrs.org/browse/SDK-279
This is a substantial refactor of the Setup process. If I've done everything correctly, this should have no functional impact. There is what appears to be a pretty good suite of tests called SetupIntegrationTest, which provides some confidence.
I am refactoring it mainly because the logic for resolving the distro.properties file was scattered about, so that no one at any point had much confidence what distro.properties looked like, or even that it was non-null.
> SDK-279: Refactor SDK setup

- docker-maven-plugin/pom.xml
- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractDockerMojo.java
- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateMySql.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- pom.xml
JIRA Issue: https://issues.openmrs.org/browse/SDK-285
Talk thread: https://talk.openmrs.org/t/why-the-sdk-can-not-find-this-plugin/33644
> SDK-285: Cannot create Docker container on Linux

- README.md
- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/ServerUpgrader.java
https://issues.openmrs.org/browse/SDK-283
> SDK-283  SDK deploy should update microfrontends

- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildDistroIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
https://issues.openmrs.org/browse/SDK-288
> SDK-288  SDK build-distro should build SPA application

- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
> Print the openmrs frontend tool version number when running SPA install

- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIntegrationTest.java
- integration-tests/src/test/resources/integration-test/openmrs-distro.properties
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
https://issues.openmrs.org/browse/SDK-290
> SDK-290: Should be possible to specify `openmrs` frontend version

- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- pom.xml
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/PropertiesUtils.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/VersionsHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
This allows developers to deploy the O3 reference applications with the SDK.
Jira ticket: https://issues.openmrs.org/browse/SDK-306
> SDK-306: Integrated Micro Frontend Tooling Setup in OpenMRS SDK

- integration-tests/src/test/resources/integration-test/buildIT/module1/pom.xml
- integration-tests/src/test/resources/integration-test/buildIT/module2/pom.xml
- pom.xml
Update the source and target Java version to 1.8.
Jira ticket: https://issues.openmrs.org/browse/SDK-307
> SDK-307: Update source and target Java version to 1.8.

- integration-tests/pom.xml
Jira ticket: https://issues.openmrs.org/browse/SDK-310
> SDK-310: Update integration test version to 4.7.0-SNAPSHOT

- archetype-module-platform/pom.xml
- archetype-module-refapp/pom.xml
- archetype-submodule-owa/pom.xml
- docker-maven-plugin/pom.xml
- integration-tests/pom.xml
- maven-plugin/pom.xml
- pom.xml
- sdk-commons/pom.xml
- tomcat7-maven-plugin/pom.xml
- tomcat9-maven-plugin/pom.xml
Jira ticket: https://issues.openmrs.org/browse/SDK-313
> SDK-313: Bump the SDK version to 5.0.0 SNAPSHOT

- maven-plugin/src/main/resources/help.yaml
Changing DspaCoreVersion to DappShellVersion.
> Updating documentation

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/NodeHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
Add legacy-peer-deps argument to npm commands.
jira ticket: https://issues.openmrs.org/browse/SDK-317
> SDK-317: Mitigating Module not found error when building the frontend

- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/resources/build-distro/docker-compose.yml
- maven-plugin/src/main/resources/build-distro/web/startup.sh
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
jira ticket: https://issues.openmrs.org/browse/SDK-316
> SDK-316: Enable deploying O3 from build-distro plugin

- pom.xml
This resolves the `java.lang.NoSuchMethodError: com.google.common.base.Platform.stringIsNullOrEmpty` error when starting docker containers.
see https://openmrs.atlassian.net/browse/SDK-324
- [] I have **added tests** to cover my changes. (If you refactored
No? Unsure? -> execute …
> SDK-324: openmrs-sdk:run" not working with SDK version 5.4.0

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
see https://openmrs.atlassian.net/browse/SDK-323
> SDK-323: Adding support for users to pass JVM argument using the SDK

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
- maven-plugin/src/main/resources/help.yaml
> SDK-323: Adding support for users to pass JVM argument using the SDK (Updating the documentation)

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
In distro properties after 3.0.0-beta.16 frontend properties have been moved to the spa-assemble-config.json. This provides support for that.
> Resolving the null pointer error in the latest O3 snapshot setup

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/PropertiesUtils.java
Using 'org.openmrs.distro:referenceapplication-frontend' artifact for extracting frontend distro properties when setting up new O3 versions, specifically targeting versions 3.0.0-beta.17 and above.
> Using referenceapplication-frontend to extract frontend properties

- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractDockerMojo.java
> SDK-329: Remove hard-coded dependency on Docker Engine API version

- maven-plugin/src/main/resources/help.yaml
> Updating output to Doutput in help

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Help.java
On the latest version of the SDK when we run mvn openmrs-sdk:help outside the project directory we get the following error. 
```
mvn openmrs-sdk:help
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- openmrs-sdk-maven-plugin:5.8.0:help (default-cli) @ standalone-pom ---
[WARNING] The POM for org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:jar:1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------ …
```
> Fix Maven Project Version Retrieval for Help Plugin Outside Project Directory

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
This PR addresses an issue where the SDK failed to extract configuration due to a file rename. It corrects the extraction process so the configurations are properly handled from the downloaded zip file.
> Resolve the Configuration Extraction Error for O3

- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractDockerMojo.java
- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateMySql.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DBConnector.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DockerHelper.java
Update the MySQL from 5.6 to 8.4.1
> Update the MySQL version to 8.4.1

- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
This allows to inherit distro.properties files. If you want to setup a 3.1.0-SNAPSHOT you could use the following distro.properties file.
```
name=Ref 3.x distro new
distro.artifactId=distro-emr-configuration
distro.groupId=org.openmrs
version=3.1.0-SNAPSHOT
```
You can customize the setup by overriding default properties or produce new ones by adding them to the distro.properties file. Here’s an example that adds a SPA module and updates the version of webservices.rest:
```
name=Ref 3.x distro new
distro.artifactId=distro-emr-configuration
distro.groupId=org.openmrs
version=3.1.0-SNAPSHOT
omod.spa=2.0.0-SNAPSHOT
omod.webservices.rest=2.45.0-SNAPSHOT
```
see https://openmrs.atlassian.net/browse/O3-3431
No? Unsure? -> [configure your …
> O3-3424: Distro Inheritance Tool

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
This update enables users to specify exclusions in the openmrs-distro.properties file. These exclusions prevent certain modules from being inherited from the parent distro.properties file, allowing for more tailored configurations.
ex: This will exclude `legacyui module`, `esm-login-app `and `webservices.rest` from the distro-emr-configuration:3.1.0-SNAPSHOT when creating the server.
```
name=Reference Application
parent.artifactId=distro-emr-configuration
parent.groupId=org.openmrs
parent.version=3.1.0-SNAPSHOT
exclusions=omod.legacyui,spa.frontendModules.@openmrs/esm-login-app,omod.webservices.rest
```
see https://openmrs.atlassian.net/browse/O3-3440
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the …
> O3-3440: Support for Exclusions in distro.properties

- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
Adding distro inheritance support to the build-distro plugin.
see https://openmrs.atlassian.net/browse/O3-3431
> O3-3426: Distro Inheritance Tool for the Build-Distro plugin

- integration-tests/pom.xml
- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIT.java
- integration-tests/src/test/resources/integration-test/invokeIT/pom.xml
- integration-tests/src/test/resources/log4j2.xml
- pom.xml
see https://openmrs.atlassian.net/browse/SDK-359
> SDK-359 - Upgrade commons-io and add logging to integration tests

- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildDistroIT.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIT.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIT.java
- integration-tests/src/test/resources/integration-test/openmrs-distro-content-package-no-namespace.properties
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/ServerUpgrader.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/ContentHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/ContentHelperTest.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/ContentPackage.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/ContentProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistributionBuilder.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- sdk-commons/src/test/java/org/openmrs/maven/plugins/model/DistroPropertiesTest.java
see https://openmrs.atlassian.net/browse/SDK-346
see https://openmrs.atlassian.net/browse/SDK-363
see https://openmrs.atlassian.net/browse/SDK-364
> SDK-346, SDK-363, SDK-364 - Improvements to content package loading

- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
> Updating the docker container prompt

- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIT.java
see https://openmrs.atlassian.net/browse/SDK-379
> SDK-379: Catch and Log Errors in assertSuccess to Prevent CI Failures

- .github/workflows/maven.yml
- pom.xml
This resolves the `java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'` when trying to compile with Java 21.
No? Unsure? -> execute command `git pull …
> Update lombok to 1.18.38

- .github/workflows/maven.yml
- pom.xml
Added explicit annotationProcessorPaths to the maven-compiler-plugin to resolve 'cannot find symbol' errors for Lombok-generated access modifiers under Java 24.
see https://openmrs.atlassian.net/browse/SDK-380
> SDK-380: Add support for Java 24

- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
see https://openmrs.atlassian.net/browse/SDK-381
> SDK-381: Make Node.js and NPM versions configurable via distro.properties, env vars, or system properties

- maven-plugin/src/main/resources/settings.xml
Follow-up commit for: https://github.com/openmrs/openmrs-sdk/commit/d1bd93a455c3374a83095fb65ad42afdc128dfeb
> Add sonatype repository to settings.xml

- maven-plugin/src/main/resources/settings.xml
Followup to: https://github.com/openmrs/openmrs-sdk/commit/5063b1adbabd4f330d6d3185c6ead0cf13c2ec9f
> Add sonatype-nexus repository to settings.xml

- tomcat9-maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
see https://openmrs.atlassian.net/browse/SDK-388
> SDK-388: Support OpenMRS Platform 3.x as a valid server platform version in SDK

- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
This PR enhances the OpenMRS SDK setup wizard by allowing users to manually enter a specific version of the server they are trying to setup that may not be listed in the default options.
- A new option, "Enter Specific Version", is now available in the version selection menu.
- When selected, the wizard prompts the user to input a version string, which is then used for the setup process.
see https://openmrs.atlassian.net/browse/SDK-389
added all formatting changes to …
> SDK-389: Add Enter Specific Version Option in server setup process

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
- pom.xml
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/JDKVersionHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
- tomcat11-maven-plugin/pom.xml
- tomcat11-maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
- tomcat11-maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/OpenMRSSDKRedirectServlet.java
- tomcat11-maven-plugin/src/test/java/org/openmrs/maven/plugins/utility/OpenMRSSDKRedirectServletTest.java
see https://openmrs.atlassian.net/browse/SDK-391
> SDK-391:Add support to running Platform 3.X servers

- bamboo-specs/bamboo.yml
This adds a Bamboo CI/CD specification file that defines the build pipeline for the OpenMRS SDK. Add support to Java 8 - 24 builds.
see https://openmrs.atlassian.net/browse/SDK-393
> SDK-393: Add Support for Bamboo Spec
