- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SdkMatchers.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/Bintray.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/OpenmrsBintray.java
It is follow-up to #20. Introduced changes:
- when deploying OWA, server is checked if it has OWA module. If not, its latest version is installed
- `Bintray` class methods are non-static
- I left option to install OWA in custom directory(explained here https://github.com/openmrs/openmrs-sdk/pull/20#discussion_r68741143), but commented it better in code. If we decide we won't support this, I will delete this feature.
> SDK-86 install OWA module when deploying OWA if not installed yet

- maven-plugin/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Pull.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/CompositeException.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Project.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
- pom.xml
So, I'm not really sure if I did it in the proper way, but when catching exception instead of throwing one I'm setting the failureReason which is then printed to the user. 
I didn't throw for example RuntimeException, because I think it's better to try pull changes for every watched module and thet print which one were updated successfully and which one wasn't.
Another thing is when calling git.stashApply there is no way to check the stash message if there were any conflicts(like you can when doing pull rebase) so I'm reverting all changes in catch block.
> SDK-102 openmrs-sdk:pull added

- archetype-module-refapp/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetype-module-refapp/src/main/resources/archetype-resources/api/pom.xml
- archetype-module-refapp/src/main/resources/archetype-resources/api/src/main/resources/messages.properties
- archetype-module-refapp/src/main/resources/archetype-resources/omod/pom.xml
- archetype-module-refapp/src/main/resources/archetype-resources/pom.xml
- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/CreateProjectIntegrationTest.java
- integration-tests/src/test/resources/integration-test/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateProject.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
- replace invoking `openmrs-contrib-maven-plugin-module-wizard` with own wizard and execute project generation without `MojoExecutor`
- change refapp module archetype parameters to align to convention from other archetypes (`A-moduleName` to `module-name` etc.) 
- add tests to CreateProject and delete redundant properties from test pom.xml
> SDK-109 Introduce wizard for modules

- maven-plugin/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Pull.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/PullRequest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/git/DefaultGitHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/git/GitHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/git/GithubPrRequest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultJira.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Jira.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Project.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/PullRequestTest.java
- pom.xml
https://issues.openmrs.org/browse/SDK-116
- add `PullRequest` task, works as described in issue
- use `EGit` to interact with GitHub API
- add `GitHelper` interface to encapsulate interactions with Git and GitHub, and its implementation in DefaultGitHelper
- use `jira-rest-java-client` to fetch data from `issues.openmrs.org`
- add `Jira` interface to encapsulate interactions with Jira, with implementation
- add Mockito dependencies and unit tests to `PullRequest`
> SDK-116 Create and update pull request

- maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateProject.java
reference application module archetype doesn't need additional archetypes, I have overlooked that earlier.
> SDK-109 followup - fix creating refapp module

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
Small fix, we noticed that if user wants to deploy module running sdk with flags(`-DartifactId=...` etc.) interactive mode with prompt asking what sdk has to do showes up anyway. This PR fixes it.
> SDK-86 followup: fix deploying module with flags

- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/CreateProjectIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/PullIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateProject.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
- extend `Wizard` interface with method to prompt options without setting message and default value for custom
- add `testMode` property to tasks to easily disable interactive mode without batch answers
- resolve available reference application versions dynamically by using `VersionsHelper,` instead of hard-coded values
> SDK-119 Improve wizard

- maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- add logic to prevent creating new server in already existing directory
- improve logic of resolving suggested reference application versions, now it should work fine no matter which versions user has in maven local repository
- replace error with warning when running OpenMRS platform 1.x with JDK 8
> SDK 126 - multiple fixes 

- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractDockerMojo.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
Docker plugin doesn't find container when name is passed, because java-docker appends "/" prefix to every container name.
> SDK-130 fix query in searching container by name

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Delete.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
Before deleting server DB we are running docker container if server was dockerized
If there is no servers available, then throw RuntimeException when asked for existing serverId
> SDK-126 fixes in delete goal

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Delete.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
* improve logic to detect mysql connection. Before, SDK didn't recognize mysql URI if there was a typo in "jdbc:mysql" part. Now it does and fails to connect, which interrupts setup
* add rollback to `setup` - when setup is interrupted, SDK deletes unfinished server
* `delete` fails when dropping DB fails, instead of showing error log
> SDK-133 stop failing silently, add rollback to setup task

- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractDockerMojo.java
Had to fix Docker API version, because docker-java library is not compatibile with new version 1.24, so it has to be explicitly declared in docker client initialization.
> SDK-138 Fix container searching, set fixed docker api version

- integration-tests/src/test/java/org/openmrs/maven/plugins/SdkMatchers.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- integration-tests/src/test/resources/integration-test/openmrs-distro.properties
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateProject.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Pull.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/PullRequest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Server.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DockerHelper.java
@rkorytkowski 
I've changed the property options a little bit. You can specify three values in distro.properties:
1) property.%propertyName%=value
2) property.%propertyName%.prompt=value
3) property.%propertyName%.default=value
With option 1 specified wizard won't prompt for this value, if there will be only option 2 wizard will ask for value with specified prompt(option 3 is optional for default value)
The properties are then saved in openmrs-server.properties as %propertyName%=value.
The property.%propertyName% form distro can be override be passing -DpropertyName=value in command line.
Unfortunately putting properties in openmrs-servers.properties and setting them as system properties doesn't seem to solve @mogoodrich problem, I guess pih.config is not read as system value. I managed …
> SDK-134 Allow setting values in openmrs-runtime.properties

- integration-tests/src/test/java/org/openmrs/maven/plugins/CloneIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Clone.java
Issue was caused by different Github HTTP key extracted from project's pom.xml
There are many different `scm.url` syntax conventions, so they need to be handled by method that makes them universal.
> SDK-161 - Fixed GitHub HTTP Key parsing

- docker-maven-plugin/pom.xml
- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractDockerMojo.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DockerHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
@rkorytkowski 
I am checking for **Docker for Windows** by executing HTTP Request to `http://127.0.0.1:2375/` and it works fine, but I am trying to do same for **Docker for Mac** and I don't know whats default URL in this case (I've temporary set it to `tcp://127.0.0.1:2375/`, which probably isn't correct).
It would be nice if You test is on Mac and tell me what should I put into `DEFAULT_HOST_DOCKER_FOR_MAC` constant.
You can build this code on Mac to test it, since You will be prompted for Docker host URL (if `tcp://127.0.0.1:2375/` as default Docker for Mac host address is incorrect)
> SDK-187 - Added support for Docker for Windows and Mac

- maven-plugin/src/main/resources/build-distro/docker-compose.yml
By adding `/usr/local/tomcat/.OpenMRS/modules/` and `/usr/local/tomcat/.OpenMRS/owa/` to `web` service's `volumes` its possible to separate `modules` and `owa` directories content from docker volume, so every container got its own `modules` and `owa` content.
> SDK-191 - Store OpenMRS data in volume

- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildIntegrationTest.java
- maven-plugin/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Build.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/BuildOwaTest.java
- maven-plugin/src/test/java/resources/package.json
Now there are 4 places where npm and nodejs version could be described (order by priority):
1. Batch argument (described as `npmVersion` and `nodejsVersion`)
2. System version
3. OWA Project version (described as properties: `npm-version` and `nodejs-version` in `package.json`)
4. Default version.
> SDK-195 - Build owa uses system version

- README.md
added bintray readme badge for latest version to show devs where its
hosted so they can easily find all related release infos, urls (website, issue
tracker) and dependency snippet
> Add bintray readme badge for latest version

- integration-tests/src/test/java/org/openmrs/maven/plugins/OpenmrsBintrayIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Fetch.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Release.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/Bintray.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/OpenmrsBintray.java
if you access internet through a proxy, the download of binary files via HTTP fails.
This change allows the maven-plugin of the SDK to use the proxy information stored in the global settings to connect to internet and to download files.
> Use proxy for bintray downloads

- .travis.yml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
As part of the PR:
Link to the Ticket: https://issues.openmrs.org/browse/SDK-243
> SDK-243 | Fix query to reset search indexes.

- pom.xml
See [SDK-245](https://issues.openmrs.org/browse/SDK-245).
The SDK is using a version of Tomcat that doesn't appropriately handle Jars built with the Java Module System. This PR simply bumps the version of Tomcat to a version in the 7.x series that supports these Jars.
> SDK-245: Upgrade Tomcat version in SDK

- maven-plugin/src/main/java/org/openmrs/maven/plugins/RunTomcat.java
- pom.xml
Description of what I did:
I enabled  the display of the  the server url on the last line before calling jetty url as "OpenMRS is ready for you at http://localhost:8080/openmrs/" . To achieve this, I did the following:
1. import org.apache.catalina.LifecycleEvent , import org.pache.catalina.LifecycleListener; and  import org.apache.catalina.LifecycleListener; because they are used inside the OpenmrsStartListener.
2. Added OpenmrsStartListener class
3. Display the message requested per the ticket description.
4. I changed `<source 1.7</source>` to `<source>8</source>` and likewise for `<target>`. so that, i can take advantage of Java 8’s lambda expressions 
Issue worked on:
https://issues.openmrs.org/browse/SDK-18
> SDK-18: Display friendly message when server is ready

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
Description of what I did:
I worked on an option where by when a port is taken while running openmrs SDK, the SDK should not only suggests un alternative port to be used but also  allow a user to specify a port they want to use. To achieve this I took the input to the wizard prompt and turn it into the port value which is returned by the value of the promptForValueIfMIssingWithDefault() function.
Ticket worked on:
https://issues.openmrs.org/projects/SDK/issues/SDK-222?filter=allopenissues
> SDK-222: Allow user to specify port to use when default taken

- maven-plugin/src/main/resources/openmrs-platform.sql
This pull request adds two records to the `liquibasechangelog` table.
Without those values updating the database with the new Liquibase snapshots introduced by 2.4.0-SNAPSHOT is failing.
Creating, starting and restarting servers was successfully tested for both OpenMRS 2.3.0 and 2.4.0-SNAPSHOT.
> TRUNK-4830 Avoid running legacy liquibase changesets

- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
https://issues.openmrs.org/browse/SDK-230
During SDK setup, if a user attempts to use an empty password to connect to a database,  JDBC throws a connection error.
> SDK-230: Allow empty string passwords in JDBC

- maven-plugin/src/main/java/org/openmrs/maven/plugins/model/Artifact.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/model/ArtifactTest.java
This changes `getDestFileName()` to only remove "-omod" rather than whatever was at the end of the dash. This is useful for supporting OWAs (and other artefacts we may need to support).
> SDK-275: Support module names with dashes

- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- integration-tests/src/test/resources/integration-test/openmrs-distro.properties
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/utility/SpaInstallerTest.java
- maven-plugin/src/test/resources/test-tmp/.gitignore
This adds support for SPA parameters that take array arguments. Right now this is just `configUrls`.
> SPA installer should handle array-type config parameters correctly

- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/NodeHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/NodeProxyHelper.java
[SDK-291](https://issues.openmrs.org/browse/SDK-291). This overrides the broken behaviour in maven-frontend-plugin 1.11.3 and replaces it with appropriate behaviour. Also adds some basic handling for the `nonProxyHosts` configuration setting.
> SDK-291: Maven proxy settings should be appropriately passed to Node

- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/SdkStatistics.java
- sdk-commons/src/test/java/org/openmrs/maven/plugins/model/SdkStatisticsTest.java
Jira ticket: https://issues.openmrs.org/browse/SDK-309
> SDK:309-Switching to the new Date and Time API

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
Setting up servers is problematic when the server file path contains spaces. So this adds an error message for server directories with spaces.
> Adding an error if the server path contains a space.

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Run.java
reference: https://talk.openmrs.org/t/manual-installation-build-tests-fail-at-openmrs-api/40060/12
> Removing memory-related parameters from Maven opts

- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/PropertiesUtils.java
> Fixing the null pointer error on Setup plugin

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/NodeHelper.java
- pom.xml
- sdk-commons/pom.xml
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/Server.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/PropertiesUtils.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
This updates the SDK Setup command to work with the relocated distro binaries.
see https://openmrs.atlassian.net/browse/SDK-331
> SDK-331: Update SDK to work with 3.0.0

- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/resources/build-distro/web/Dockerfile-tomcat8
see https://openmrs.atlassian.net/browse/O3-3426
> O3-3426: Update build-distro command to use Maven artifacts

- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
This makes the SDK's bundled option builds and includes the frontend in the .war file
see https://openmrs.atlassian.net/browse/O3-3430
> O3-3437: Update SDK to bundle SPA frontend into WAR

- archetype-module-refapp/src/main/resources/archetype-resources/pom.xml
- integration-tests/src/test/java/org/openmrs/maven/plugins/CreateProjectIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateProject.java
> O3-3776: Fix Content Package Template Creation

- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/VersionsHelper.java
see https://openmrs.atlassian.net/browse/SDK-332
> SDK-332: Correct the O3 Versions displayed during setup of an instance

- integration-tests/src/test/java/org/openmrs/maven/plugins/RemoveDependencyTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/RemoveDependency.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
This adds a plugin that allows users to manipulate a distro.properties file by removing dependencies.
see https://openmrs.atlassian.net/browse/O3-3434
> O3-3434: SDK Command: Remove dependencies from distro.properties

- integration-tests/src/test/java/org/openmrs/maven/plugins/AddExclusionIntegrationTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AddExclusion.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
This adds a plugin that allows users to manipulate a distro.properties file by removing exclusions.
see https://openmrs.atlassian.net/browse/O3-3439
> O3-3439: Add exclusions to distro.properties

- integration-tests/src/test/resources/integration-test/openmrs-distro.properties
- maven-plugin/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- pom.xml
- sdk-commons/pom.xml
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/Artifact.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/NpmVersionHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/PropertiesUtils.java
see https://openmrs.atlassian.net/browse/O3-3512
> O3-3512: SDK should handle reading dependencies from content.properties and ensuring they are part of the distro

- integration-tests/pom.xml
- integration-tests/src/test/java/org/openmrs/maven/plugins/AddDependencyTest.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AddDependency.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/NpmVersionHelper.java
This adds a plugin that allows users to manipulate a distro.properties file by adding dependencies. This supports adding OMOD, SPA, OWA, and WAR dependencies.
see https://openmrs.atlassian.net/browse/O3-3433
> O3-3433: SDK Command: Add dependencies to distro.properties

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/ContentHelper.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
Issue I worked on
see https://openmrs.atlassian.net/browse/O3-3639
was able to add --config-file parameter 
Running 'npm --legacy-peer-deps --cache=/tmp/openmrs-sdk-node11062473255982918384/npm-cache exec -- openmrs@5.8.0 assemble --target /scicomp/home-pure/test/openmrs/server5/frontend --mode config **--config-file /tmp/openmrs-sdk-hiv-4646429956995520647/configs/frontend_config/partner-notification.json --config-file /tmp/openmrs-sdk-hiv-4646429956995520647/configs/frontend_config/general-counselling.json --config-file /tmp/openmrs-sdk-hiv-4646429956995520647/configs/frontend_config/clinical-visits.json --config-file /tmp/openmrs-sdk-hiv-4646429956995520647/configs/frontend_config/config.json --config-file /tmp/openmrs-sdk-hiv-4646429956995520647/configs/frontend_config/program-manageme …
> O3-3639: SDK to rebuild frontend with multiple config files

- docker-maven-plugin/src/main/java/org/openmrs/maven/plugins/CreateMySql.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DockerHelper.java
@ibacher , @wikumChamith .Lost the previous pr i raised on this topic while doing a rebase.So raised a new pr and will update changes accordingly.
When setting up openmrs sdk by running mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:5.14.0-SNAPSHOT:setup i get a bunch of errors.
The first one is protocol unsupported error → This is because we use http instead of tcp to talk to docker daemon
Once the protocol error is tackeled we get the mysql image not found error ->The withImageFilterCommand doesn't seem to work. Reference https://github.com/docker-java/docker-java/issues/1516
Openmrs Talk Link - [OpenMRS SDK installation_BUILD FAILURE_Failed to setup server](https://talk.openmrs.org/t/openmrs-sdk-installation-build-failure-failed-to-setup-server/40618/7) …
> SDK-339: Fix auto Docker setup in Sdk

- archetype-module-content/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetype-module-content/src/main/resources/archetype-resources/OpenMRSFormatter.xml
- archetype-module-content/src/main/resources/archetype-resources/README.md
- archetype-module-content/src/main/resources/archetype-resources/license-header.txt
- archetype-module-content/src/main/resources/archetype-resources/pom.xml
- archetype-module-content/src/test/resources/projects/basic/reference/OpenMRSFormatter.xml
- archetype-module-content/src/test/resources/projects/basic/reference/README.md
- archetype-module-content/src/test/resources/projects/basic/reference/license-header.txt
- archetype-module-content/src/test/resources/projects/basic/reference/pom.xml
- archetype-module-platform/src/main/resources/archetype-resources/README.md
- archetype-module-platform/src/main/resources/archetype-resources/pom.xml
- archetype-module-refapp/src/main/resources/archetype-resources/OpenMRSFormatter.xml
- archetype-module-refapp/src/main/resources/archetype-resources/README.md
- archetype-module-refapp/src/main/resources/archetype-resources/license-header.txt
- archetype-module-refapp/src/main/resources/archetype-resources/pom.xml
Add Spotless for code formatting and update documentation
- Integrate Spotless Maven plugin for automated code formatting
- Configure Spotless to use OpenMRS coding standards
- Add license header application to Java and XML files
- Update README.md with instructions on running Spotless
- Remove formatter-maven-plugin in favor of Spotless
- Ensure Spotless runs automatically during the build process
- Update pom.xml to include Spotless configuration
These changes improve code consistency and make it easier for
contributors to adhere to the project's coding standards.
see https://openmrs.atlassian.net/browse/SDK-340
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit …
> SDK-340: Add Spotless for code formatting and update documentation

- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- integration-tests/src/test/resources/integration-test/openmrs-distro-spa-artifacts.properties
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/ModuleInstaller.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/SpaInstaller.java
- maven-plugin/src/test/java/org/openmrs/maven/plugins/utility/SpaInstallerTest.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
see https://openmrs.atlassian.net/browse/SDK-344
> SDK-344 - SDK should support including spa from a maven artifact

- integration-tests/src/test/java/org/openmrs/maven/plugins/AddExclusionIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/SetupIntegrationTest.java
- integration-tests/src/test/resources/integration-test/openmrs-distro-parent-as-distro.properties
- integration-tests/src/test/resources/integration-test/openmrs-distro-parent-as-parent.properties
- integration-tests/src/test/resources/integration-test/openmrs-distro-parent-distro.properties
- integration-tests/src/test/resources/integration-test/openmrs-distro-spa-artifacts.properties
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AddExclusion.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/GenerateDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/BaseSdkProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/model/DistroProperties.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DistroHelper.java
- sdk-commons/src/test/java/org/openmrs/maven/plugins/model/DistroPropertiesTest.java
- sdk-commons/src/test/java/org/openmrs/maven/plugins/utility/DistroHelperTest.java
see https://openmrs.atlassian.net/browse/SDK-354
> SDK-354 - Fixing bugs and adding test cases for the AddExclusions goal

- .github/workflows/maven.yml
- integration-tests/pom.xml
- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractMavenIT.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/AbstractSdkIT.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/BuildIT.java
- integration-tests/src/test/java/org/openmrs/maven/plugins/utility/ArtifactHelperIT.java
- integration-tests/src/test/resources/integration-test/invokeIT/pom.xml
- maven-plugin/pom.xml
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AbstractTask.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/InvokeMethod.java
- pom.xml
- sdk-commons/pom.xml
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/ArtifactHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/MavenEnvironment.java
see https://openmrs.atlassian.net/browse/SDK-358
> SDK-358 - Add integration test framework for helper classes

- integration-tests/src/test/java/org/openmrs/maven/plugins/DeployIT.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/AddDependency.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/BuildDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Deploy.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/GenerateDistro.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/SDKConstants.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/VersionsHelper.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
- sdk-commons/src/test/java/org/openmrs/maven/plugins/utility/VersionsHelperTest.java
see https://openmrs.atlassian.net/browse/SDK-361
see https://openmrs.atlassian.net/browse/SDK-356
See ticket details for description of changes.
> SDK-361 and SDK-356 - Update wizard to support custom distributions and more platform and distribution versions

- maven-plugin/src/main/java/org/openmrs/maven/plugins/Setup.java
- maven-plugin/src/main/java/org/openmrs/maven/plugins/utility/DBConnector.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/Wizard.java
see https://openmrs.atlassian.net/browse/SDK-368
> SDK-368: SDK should prompt for the database logins again if invalid logins were entered

- sdk-commons/pom.xml
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DefaultWizard.java
- sdk-commons/src/main/java/org/openmrs/maven/plugins/utility/DockerHelper.java
see https://openmrs.atlassian.net/browse/SDK-377
> SDK-377: Prompt Users with Existing Docker Containers for Database Setup
